apiVersion: apps/v1
kind: Deployment
metadata:
  name: maveneo
  labels:
    app: maveneo
    release: v01
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: maveneo
      release: v01
  template:
    metadata:
      labels:
        app: maveneo
        release: v01
    spec:
      containers:
        - name: maveneo
          image: "mibingo/maveneo:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          