apiVersion: v1
kind: Service
metadata:
  name: maveneo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30036
  selector:
    app: maveneo
    release: v01
